name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: challenge-alegra-cluster

jobs:
  deploy:
    name: Deploy Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy orders-app to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: orders-task-def.json
          cluster: ${{ env.CLUSTER_NAME }}
          service: orders-service
          wait-for-service-stability: true

      - name: Deploy kitchen-app to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: kitchen-task-def.json
          cluster: ${{ env.CLUSTER_NAME }}
          service: kitchen-service
          wait-for-service-stability: true

      - name: Deploy inventory-app to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: inventory-task-def.json
          cluster: ${{ env.CLUSTER_NAME }}
          service: inventory-service
          wait-for-service-stability: true