name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CLUSTER_NAME: challenge-alegra-cluster
  IMAGE_TAG_ORDERS: ${{ secrets.IMAGE_TAG_ORDERS }}
  IMAGE_TAG_INVENTORY: ${{ secrets.IMAGE_TAG_INVENTORY }}
  IMAGE_TAG_KITCHEN: ${{ secrets.IMAGE_TAG_KITCHEN }}

jobs:
  deploy:
    name: Deploy Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 🔹 Renderizar task definition con la imagen correcta para orders
      - name: Render Orders Task Definition
        id: render_orders
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/ecs-tasks/orders-task-def.json
          container-name: orders-container
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/alegra-challenge:${{ env.IMAGE_TAG_ORDERS }}

      # 🔹 Renderizar task definition con la imagen correcta para kitchen
      - name: Render Kitchen Task Definition
        id: render_kitchen
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/ecs-tasks/kitchen-task-def.json
          container-name: kitchen-container
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/alegra-challenge:${{ env.IMAGE_TAG_KITCHEN }}

      # 🔹 Renderizar task definition con la imagen correcta para inventory
      - name: Render Inventory Task Definition
        id: render_inventory
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/ecs-tasks/inventory-task-def.json
          container-name: inventory-container
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/alegra-challenge:${{ env.IMAGE_TAG_INVENTORY }}

      - name: Deploy orders-app to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ env.CLUSTER_NAME }}
          service: orders-service
          task-definition: ${{ steps.render_orders.outputs.task-definition }}
          wait-for-service-stability: true

      - name: Deploy kitchen-app to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ env.CLUSTER_NAME }}
          service: kitchen-service
          task-definition: ${{ steps.render_kitchen.outputs.task-definition }}
          wait-for-service-stability: true

      - name: Deploy inventory-app to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ env.CLUSTER_NAME }}
          service: inventory-service
          task-definition: ${{ steps.render_inventory.outputs.task-definition }}
          wait-for-service-stability: true
